nvim-telescope/telescope-frecency.nvim

- lua/telescope/_extensions/frecency/db_client.lua
Without this, `ignore_patterns` settings will be ignored.
> Detect ignore_patterns in validating DB

- lua/telescope/_extensions/frecency.lua
I re-mapped `<C-n>` in settings, but it is ignored with loading frecency. I noticed calling `apply_keymap()` causes this.
Without calling, it still seems to work all features including Workspace Filters. Is this needed?
```lua
config = function()
local telescope = require"telescope"
local actions = require"telescope.actions"
telescope.setup{
defaults = {
mappings = {
i = {
["<C-j>"] = actions.move_selection_next,
["<C-k>"] = actions.move_selection_previous,
["<C-n>"] = actions.goto_file_selection_split,
},
},
},
extensions = {
frecency = {
workspaces = {
vimrc = vim.env.HOME.."/.config/nvim",
},
},
},
}
telescope.load_extension"frecency"
end,
```
Full reproducible [Dockerfile][]
[Dockerfile]: https://gist.github.com/delphinus/50b959cc5301d843661ac6718cdc419d
> Disable unneeded overriding mappings

- lua/telescope/_extensions/frecency.lua
- lua/telescope/_extensions/frecency/db_client.lua
- plugin/frecency.vim
set the config option `opts.db_safe_mode = false` to disable the prompt when the db validation function is going to remove more than <safety threshold>(10) entries at once.
> feat: allow user to disable database validation safe_mode

- README.md
> Fix a typo in the Packer install instructions

- README.md
- lua/telescope/_extensions/frecency.lua
Add a `default_workspace` setting which if set to something other than nil, is used by default.
Re #39, I can get the picker to scope to the current working directory only by using a Telescope setting like the following
```lua
extensions = {
frecency = {
default_workspace = 'CWD',
},
}
````
Then to scope back to everything I put a non-existent workspace tag in my query like `:*:` or `:blah:` (not sure if this is intentional or not)
If this setting could be useful I can add some documentation
> Add default_workspace setting

- lua/telescope/_extensions/frecency.lua
Hi,
Currently when you set `show_filter_column` to `true` you get something like:
This PR fixes that
> fix: only show filter column when show_filter_column is true

- lua/telescope/_extensions/frecency.lua
> fix: show icon before directory

- lua/telescope/_extensions/frecency.lua
Currently LSP workspaces are only fetched when user triggers `:<Tab>` completion. So, if you set your `default_workspace` to `LSP`, it doesn't work.
With the changes of this PR, LSP workspaces will be fetched as soon as LSP is attached to a buffer, so it'll work after that.
> fix: fetch lsp workspaces without triggering tag completion

- README.md
The old repository on github redirects to this one.
> Update url for sqlite dependency

- lua/telescope/_extensions/frecency/db_client.lua
- lua/telescope/_extensions/frecency/sql_wrapper.lua
`print()` causes [hit-enter][] prompts when we are using `set cmdheight=0` in the latest Neovim.
```
Telescope-Frecency: Imported 2 entries from oldfiles.
Press ENTER or type command to continue  
```
[hit-enter]: https://neovim.io/doc/user/message.html#hit-enter
Neovim has [vim.notify][] for such cases. We can overwrite it with other plugins, such as [rcarriga/nvim-notify][], so that Neovim does not show the prompt and not block outputs.
[vim.notify]: https://neovim.io/doc/user/lua.html#vim.notify()
[rcarriga/nvim-notify]: https://github.com/rcarriga/nvim-notify
> Use vim.notify not to block outputs

- lua/telescope/_extensions/frecency.lua
Some telescope.nvim's builtin pickers support `path_display` option to customize its way to show filenames. This PR brings it here.
See [:h telescope.defaults.path_display](https://github.com/nvim-telescope/telescope.nvim/blob/bd9e8a7eac1b3f921d293866abf7574d49cb610c/doc/telescope.txt#L261).
When you do not set `path_display`, it uses the same way as previous one.
```lua
require("telescope").extensions.frecency.frecency {
path_display = { "shorten", "absolute" },
-- or you can set func to edit
path_display = function(_, filename)
-- edit here
return filename
end,
}
```
> Use opts.path_display to customize

- README.md
- lua/telescope/_extensions/frecency.lua
This PR enables to accept a table for the `show_filter_column` option. The current build shows the tail of paths for `'CWD'` and `'LSP'` tags only. You can use the same way for any tag with setting this option.
> Enable to specify tags to show the tails

- lua/telescope/_extensions/frecency.lua
**Before**
Matches space separated queries, but hides everything else:
Can not fuzzy search:
**After**
Supports fuzzy search and biased towards frecency order.
> feat: use sorter fuzzy_with_index_bias

- README.md
MDN appear to have removed the Frecency Algorithm page linked in the README document. Updating link to use archived version.
> Fix broken Frecency Algorithm link in README.md

- lua/telescope/_extensions/frecency.lua
Vimscript funcs `health#foo`'s are now deprecated. This PR makes it use the new API and adds an optional dependency check for nvim-web-devicons.
> Use new API and add check for nvim-web-devicons

- lua/telescope/_extensions/frecency.lua
- lua/telescope/_extensions/frecency/db_client.lua
- lua/telescope/_extensions/frecency/sql_wrapper.lua
I found it does not show newly created files in results until I restart Neovim. This is because `db_client.get_file_scores()` is called only once if the filter is not updated.
1. Launch Neovim.
2. `:e ~/foo.txt`
3. Launch telescope-frecency:
- And we cannot see `~/foo.txt` in results.
This patch changes the logic to call `get_file_scores()` again when an entry is added to the table in autocmd events, especially `BufWritePost`.
> Detect entries when it has added new ones

- lua/telescope/_extensions/frecency.lua
#73 has introduced fuzzy matcher but it breaks score-based sorting. This fixes it.
1. Open telescope-frecency
2. With `fuzzy_with_index_bias`, it breaks sorting.
3. With `get_substr_matcher`,
it does not.
> fix: use substr matcher to use sorting by scores

- lua/telescope/_extensions/frecency.lua
This reverts commit e8e97eeebdfc2e678f88fdf2ddf9cf2c82b16030.
This plugin defines the filetype `frecency` to use a customized syntax to highlight tags in input characters. So we should use `frecency` here.
> Revert "fix: set prompt filetype to `TelescopePrompt` (#81)"

- lua/frecency/async_finder.lua
- lua/frecency/types.lua
Add typings for async functions in `plenary.async`.
> chore: add types for plenary.async

- lua/frecency/frecency.lua
- lua/frecency/picker.lua
The current logic can get candidates sufficiently fast. Remove logic for caching feature that still remained.
----
NOTE: My box has a DB containing 1284 files and 2973 timestamps. `:Telescope frecency` takes around 20 milliseconds on average.
> refactor: remove logic for caching feature

- lua/frecency/frecency.lua
This adds default highlight links.
| before | after |
|--|--|
| <img width="434" alt="スクリーンショット 0005-08-25 23 15 41" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/1239245/209acec9-5542-4b1a-a7ba-f9746bde10ca"> | <img width="434" alt="スクリーンショット 0005-08-25 23 12 20" src="https://github.com/nvim-telescope/telescope-frecency.nvim/assets/1239245/2eae9315-1616-4a61-9da0-2decc8e40821"> |
> feat: set default highlights

- lua/frecency/picker.lua
This PR contains two fixes related to workspace filtering features that seem to have been recently broken.
1. The finder contents not being updated because `finder:start()` was being called directly after the finder init, resulting in `opts.updated_finder` not being set in the picker.
2. Showing the filter column for the default workspace if the setting is enabled.
closes #149
> fix: workspace filtering

- .github/workflows/ci.yml
- README.md
- lua/frecency/database.lua
- lua/frecency/database/native.lua
- lua/frecency/database/sqlite.lua
- lua/frecency/frecency.lua
Fix #91 
This totally removes the dependencies for [kkharji/sqlite.lua](https://github.com/kkharji/sqlite.lua).
> feat!: make `use_sqlite = false` be the default

- README.md
- lua/frecency/finder.lua
- lua/frecency/frecency.lua
- lua/frecency/picker.lua
- lua/frecency/types.lua
Fix #155, #154
This introduces a feature that it can reads workspace files by external commands: [rg](https://github.com/BurntSushi/ripgrep) or [fd](https://github.com/sharkdp/fd).
pros: This achieves gathering candidates extremely faster than the native Lua code.
cons: None. It fallbacks to Lua code when `rg` and `fd` fail.
> List up entries for workspace files by `rg` or `fd`

- README.md
- lua/frecency/finder.lua
v0.9.x does not have `vim.system`, so use plenary.job instead.
----
plenary.job cannot handle NUL characters in stdout but `vim.system` does. So I removed the feature for it and from README.
> fix: add fallback for v0.9 that has no vim.system

- lua/frecency/frecency.lua
Now you can use `expand()` string to show up entries by `cwd` param.
```vim
:Telescope frecency workspace=CWD cwd=~
:Telescope frecency workspace=CWD cwd=%:p:h
```
> feat: expand cwd param

- README.md
- lua/frecency/frecency.lua
Fix: #50
Fix: #167
Before this, `db_safe_mode = false` makes it no confirmation in
`:FrecencyValidate!`, but it still does in `:FrecencyValidate` and the
auto validation in Neovim's startup.
After this commit, `db_safe_mode = false` makes it no confirmation
always when you see.
And `force` option in `Frecency:validate_database(force)` now means
weather it should remove files less than threshold.
> fix!: no confirm always when `db_safe_mode` is off

- README.md
- lua/frecency/database/native.lua
- lua/frecency/finder.lua
- lua/frecency/frecency.lua
- lua/frecency/fs.lua
- lua/frecency/os_util.lua
- lua/frecency/picker.lua
This fixes problems below.
* `:Telescope frecency` with `workspace` option causes redundant paths and users cannot open files in Windows. (detail in #164)
* The default value of `ignore_patterns` does not make sense in Windows (#169)
> fix: fix joining paths in Windows

- README.md
- lua/frecency/finder.lua
- lua/frecency/frecency.lua
- lua/frecency/picker.lua
Fix #175 
With the new option:`hide_current_buffer`, frecency does not show the buffer the cursor was on when `:Telescope frecency` is called.
```lua
-- Set this in startup
telescope.setup {
extensions = {
frecency = {
hide_current_buffer = true,
},
},
}
```
```vim
-- Overwrite config setting
:Telescope frecency hide_current_buffer=true
```
> feat: `hide_current_buffer` option

- lua/telescope/_extensions/frecency.lua
Due to performance, now it disables registration process in floating
windows.
> fix!: disable registration for floating windows

- lua/frecency/config.lua
The previous logic makes it ignore nullable config values.
> fix: detect nullable config values

- README.md
- lua/frecency/config.lua
ref #190
Use `T[]` instead of `table<integer, T>` for consistency.
> docs: add more notes & fix type annotations

- README.md
- lua/frecency/config.lua
- lua/frecency/picker.lua
fix #47 
Now `path_display` can be specified by these priorities.
1. Option specified with the command or Lua code.
- `:Telescope frecency path_display={"absolute"}`.
- or `:lua require("telescope").extensions.frecency.frecency { path_display = { "absolute" } }`.
2. `opts.extensions.frecency.path_display` in setup.
3. `opts.defaults.path_display` in setup.
```lua
require("telescope").setup {
defaults = {
-- This has the 3rd precedence.
path_display = { "absolute" },
},
extensions = {
frecency = {
-- This has the 2nd precedence.
path_display = { "shorten" },
},
},
}
```
> fix: respect telescope's `path_display`

- lua/frecency/entry_maker.lua
The current build occurs E5560 due to calling non API-fast functions in Lua loop.
```
[telescope] [WARN  18:40:20] /Users/jinnouchi.yasushi/.local/share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:669: Finder failed with msg:  ...y/telescope.nvim/lua/telescope/pickers/entry_display.lua:76: E5560: nvim_get_current_buf must not be called in a lua loop callback
```
> fix: avoid calling non API-fast funcs in Lua loop

- doc/telescope-frecency.txt
- lua/frecency/config.lua
- lua/frecency/database.lua
- lua/frecency/types.lua
Fix #200
----
Added this note in doc.
```vim
*telescope-frecency-configuration-db_root*
db_root ~
Default: `vim.fn.stdpath "state"`
Type: `string`
Path to the parent directory of custom database location. Defaults to
|$XDG_STATE_HOME|/nvim (see |stdpath()|) if unset.
NOTE: The default value was `vim.fn.stdpath "data"`. If you doesn't set this
option and you have DB in `vim.fn.stdpath "data"` instead of
`vim.fn.stdpath "state"`, it uses the one in the old path for backward
compatibility. See the detail in the issue below.
https://github.com/nvim-telescope/telescope-frecency.nvim/issues/200
```
> feat!: set the default DB path to XDG_STATE_HOME

- lua/frecency/file_lock.lua
- lua/frecency/types.lua
It fails when it gets a file lock and the parent dir does not exist. Fix it.
> fix: make the path for file_lock unless it exists

- lua/frecency/picker.lua
- lua/frecency/substr_sorter.lua
Fix #36
telescope.nvim's latest release 0.1.8 does not include the changes in https://github.com/nvim-telescope/telescope.nvim/pull/2950. So use again the original implementation.
TODO: remove this when the commit will be included in any release.
> fix: use the original sorter again

- lua/frecency/entry_maker.lua
- lua/frecency/types.lua
I commonly work with Laravel, there is a file with extension `.blade.php` and it has an individual icon (the Laravel logo). Currently in telescope-frecency, the file with that extension it still renders in the result picker with the PHP icon. FYI the nvim-web-devicons has this support for the icon at https://github.com/nvim-tree/nvim-web-devicons/pull/442 and telescope also has support for multi-part file extension at https://github.com/nvim-telescope/telescope.nvim/pull/2252. I think it would be nice to add this support in telescope-frecency. Thanks
> feat: support for multi-part file extensions

- doc/telescope-frecency.txt
- lua/frecency/database.lua
- lua/frecency/database/table.lua
- lua/frecency/finder.lua
- lua/frecency/init.lua
- lua/frecency/tests/database_spec.lua
- lua/frecency/tests/frecency_spec.lua
- lua/frecency/tests/util.lua
- lua/telescope/_extensions/frecency.lua
Fix #216 
Fix #125 
Ref #157
I added an experimental implementation. API may be changed.
```lua
local files = require("telescope").extensions.frecency.query { limit = 3 }
-- this may includes……
-- [
--   "/path/to/foo.lua",
--   "/more/path/to/bar.md",
--   "/more/and/more/path/to/foobar.txt",
-- ]
```
> feat: add frecency.query() to query DB

- lua/frecency/config.lua
Before this commit, config.setup() always succeeded the config values. With this, it uses the default values in calling.
> fix!: config.setup always reset the config

- lua/frecency/entry_maker.lua
Following PR #215, I realized I forgot to handle the fallback case for files with multi-part extensions that don't have a specific icon. For example, a file with the filename `test.js.LICENSE.txt` should render the icon for `.txt` instead of the default icon.
Here is some screenshot
Before
After
> fix(icons): improve fallback for multi-part file extensions

- lua/frecency/init.lua
With this, it does not create the frecency instance but load config with `setup()`. This decreases the delay in Neovim starting when it is launched by `nvim` only (without filenames).
> fix: do not load frecency in Neovim starting

- lua/frecency/klass.lua
This error below occurs when it takes long time to init the plugin.
E5560: nvim_echo must not be called in a lua loop callback
> fix: avoid errors caused by echoing messages

- lua/frecency/database.lua
This avoids errors when DB does not exist or has no entry.
> fix: avoid errors occured by async.util.join

- lua/frecency/klass.lua
Fix #243
It occurs an error E5560 when UI to select `y/n` by the user in validating DB. This delays it until the next tick to avoid errors.
> fix: delay calling vim.ui.select to avoid errors

- lua/frecency/web_devicons.lua
|Current|Updated|
|-|-|
|![Screenshot_20240827_194447](https://github.com/user-attachments/assets/6638c658-cb3e-4ec4-9080-26efa5555df8)|![Screenshot_20240827_194452](https://github.com/user-attachments/assets/4270109c-2ea9-4ec1-ab05-0ec9938ef556)|
The bug happens due to the nature of `nvim-web-devicons`'s `get_icon` function because it does not always return the icon name an highlight.
> ```lua
>  ...
>  if icon_data then
>    return icon_data.icon, get_highlight_name(icon_data)
>  end
> ```
Reference to the functions code: https://github.com/nvim-tree/nvim-web-devicons/blob/3722e3d1fb5fe1896a104eb489e8f8651260b520/lua/nvim-web-devicons.lua#L499-L505
Due to this, the current use `or "", ""` is not only the fallback when `ok` is false but also for regular `get_icon` calls. 
The changes …
> fix: icon colors

- lua/telescope-frecency.lua
With this, we can load telescope-frecency.nvim without `main = "frecency"` option in lazy.nvim.
> feat: enable to load without { main = "frecency" }

- lua/frecency/klass.lua
In loading frecency at Neovim startup, `vim.ui.select`'s dialog does not show message on the first line. This fixes it.
> fix: show validation message validly

- lua/frecency/init.lua
- lua/frecency/klass.lua
With this commit, it validates DB in its init phase only if it is invoked by `:Telescope frecency` or `:FrecencyDelete`.
> feat!: validate DB before execution only if needed

- lua/frecency/config.lua
- lua/frecency/database/table.lua
- lua/frecency/klass.lua
- lua/frecency/timer.lua
This makes it be enable to do this.
```bash
$ nvim --headless +'=require("frecency").query { limit = 3, json = true }' +q | jq .
[
"/path/to/most/opened/file",
"/path/to/second/file",
"/path/to/third/file"
]
```
> feat: add JSON output for query()

- doc/telescope-frecency.txt
- lua/frecency/config.lua
- lua/frecency/picker.lua
Fix #48 
In previous build, you cannot use `<Tab>`/`<S-Tab>` in insert mode in prompt
because these are used to complete workspace filters. This is reported
to be annoying, so I did a breaking change to disable this in default.
> feat!: add an option for mappings in prompt 

- README.md
- doc/telescope-frecency.txt
- lua/frecency/config.lua
- lua/frecency/database.lua
- lua/frecency/entry_maker.lua
- lua/frecency/finder.lua
- lua/frecency/klass.lua
- lua/frecency/picker.lua
Fix #264
Now you can set multiple directories into each “workspace”.
```lua
workspaces = {
CONF = "/home/my_username/.config",
DATA = "/home/my_username/.local/share",
WIKI = "/home/my_username/wiki",
PJT = {
"/home/my_username/project_foo",
"/home/my_username/project_bar",
"/home/my_username/project_foobar",
},
}
```
If you call `:Telescope frecency workspace=CONF`, you can get entries filtered out with the directory (`~/.config`) itself. In case `:Telescope frecency workspace=PJT`, you can get combined results with entries under each directories (`~/project_foo`, `~/project_bar` and `~/project_foobar`).
> feat: enable to use multi dirs for each workspace

- lua/frecency/sorter/opened.lua
- lua/frecency/sorter/same_repo.lua
- lua/frecency/tests/sorter_spec.lua
The check whether the buffer is loaded is added in the enumeration of all the buffers in the list in sorters to ensure the proper sorting.
> Check if the buffer is really opened in sorters

- doc/telescope-frecency.txt
- lua/frecency/config.lua
- lua/frecency/timer.lua
This makes `debug_timer` accept a function for tracking. This shows times with tracking messages as below, with my example class.
https://github.com/delphinus/dotfiles/blob/fd4542a648bfb49f47c85437d9ce42cbec9a3f48/.config/nvim/lua/core/utils/timer.lua
```lua
-- shows tracked times
require("core.utils.timer").pp()
```
> feat: enable to use preferable func for tracking

- lua/frecency/entry_maker.lua
Fix #289
In the former build, it has ignored `false` value for `show_filter_column`, so always shown the workspace filter name. This fixes this.
> fix: detect `show_filter_column: false` validly

- lua/frecency/web_devicons.lua
| Current | Updated |
|--------|--------|
| <img width="275" alt="Screenshot 2025-01-09 at 12 39 57" src="https://github.com/user-attachments/assets/406041cf-f8f7-415d-a110-caf5a1c5d331" /> | <img width="275" alt="Screenshot 2025-01-09 at 12 39 37" src="https://github.com/user-attachments/assets/67f30738-c402-4afa-a2b2-6639699f564a" /> | 
Let's consider the `run-tests` entry.
Currently, we have an `n...` icon because we didn't pass `opts` to `nvim-web-devicons` correctly
> fix: show incorrect default icon 

- lua/frecency/klass.lua
In calling vim.notify() while async routines, it may cause the E5560 error with unhelpful messages. Fix this.
> fix: do fallback to print() in case of E5560

- lua/frecency/v1/database.lua
When the `ignore_patterns` option is changed, it mistakenly treats ignored entries as “unlinked”, and removes them from DB. This is not an intended behavior. This fixes it.
> fix: do not remove ignored entries

- doc/telescope-frecency.txt
- lua/frecency/config.lua
- lua/frecency/init.lua
- lua/frecency/klass.lua
Fix #236
When the buffer is hidden or unloaded, this plugin marks it “unregistered” and will register again in showing the buffer (in `BufWinEnter` event). This increases the buffer's frecency score in DB.
In default, this is disabled (current at least). You can enable this with `unregister_hidden = true` in config.
> feat: unregister hidden or unloaded buffers

- lua/frecency/entry_maker.lua
Fix #309
I clean up logic to format scores shown beside candidates.
```lua
-- A means a file icon
123.4 A /path/to/file
23.4 A /path/to/file
10 A /path/to/file
5 A /path/to/file
0 A /path/to/file
-- for fuzzy matching
-- score: 5, index: 4, fuzzy_score: 5, char widths
123.4   20 -20.0 A /path/to/file
23.4   11 -10.0 A /path/to/file
10  100 24.34 A /path/to/file
5 1000 30.45 A /path/to/file
0    2 234.5 A /path/to/file
```
> fix: format scores for readability

- doc/telescope-frecency.txt
- lua/frecency/config.lua
- lua/frecency/klass.lua
Ref #108
Previously, it ignores `file_ignore_patterns` from telescope.config and also it is very confusing with `ignore_patterns` (#108).
This commit enables it detect `file_ignore_patterns` in both the picker and `frecency.query()`, and adds doc for it.
> feat: detect file_ignore_patterns from telescope
