- lua/telescope/_extensions/frecency.lua
I noticed `:Telescope frecency` get stuck some time in typing chars. So I've refactored logic to reduce time to calculate candidates.
> Refactor callback

- lua/telescope/_extensions/frecency.lua
Close https://github.com/nvim-telescope/telescope-frecency.nvim/issues/23
CC @clason
> chore: move to plenary.path

- README.md
I am pretty sure this comma shouldn't be here, as it breaks the plugin .
> Removing fatal comma

- README.md
- lua/telescope/_extensions/frecency/sql_wrapper.lua
reflect breaking changes made in https://github.com/tami5/sql.nvim/pull/105
> follow sqlite new release

- README.md
- lua/telescope/_extensions/frecency.lua
> feat: support opts.workspace

- lua/telescope/_extensions/frecency.lua
Reverts nvim-telescope/telescope-frecency.nvim#69
> Revert "fix: fetch lsp workspaces without triggering tag completion"

- lua/telescope/_extensions/frecency.lua
Currently LSP workspaces are only fetched when user triggers :<Tab> completion. So, if you set your default_workspace to LSP, it doesn't work.
With the changes of this PR, LSP workspaces will be fetched (if necessary) when the picker is opened.
---
Related PRs:
- https://github.com/nvim-telescope/telescope-frecency.nvim/pull/69
- https://github.com/nvim-telescope/telescope-frecency.nvim/pull/71
> fix: fetch lsp workspaces without triggering tag completion

- lua/telescope/_extensions/frecency/db_client.lua
Now Neovim has Lua API's to set/get/delete autocmds. Use it.
> Use the newer API to define autocmds

- lua/telescope/_extensions/frecency.lua
This reduces my startup time by about 16ms.
Resolves #30
> perf: reduce startup time by moving requires

- lua/frecency/picker.lua
> fix:can't display file name if config show_filter_column is false

- lua/frecency/frecency.lua
> fix: deal with the case called with no opts

- lua/frecency/async_finder.lua
- lua/frecency/fs.lua
- lua/frecency/tests/async_finder_spec.lua
> fix: add fs.joinpath to work in v0.9.0

- lua/frecency/async_finder.lua
- lua/frecency/finder.lua
- lua/frecency/picker.lua
- lua/frecency/state.lua
- lua/frecency/tests/async_finder_spec.lua
- lua/frecency/types.lua
> fix: clear non-matched results in results buffer

- lua/frecency/frecency.lua
> feat: deal with configs in setup()

- README.md
fix a typo or remnant of old code
> docs(readme): devicons_disabled -> disable_devicons

- lua/frecency/picker.lua
- lua/frecency/types.lua
- syntax/frecency.vim
> fix: use the default filetype for the prompt

- lua/frecency/fs.lua
ref https://github.com/nvim-telescope/telescope.nvim/issues/2552#issuecomment-1722543221
> fix: deal with the case that bufname is nil

- README.md
- lua/frecency/database.lua
- lua/frecency/database/native.lua
- lua/frecency/database/sqlite.lua
- lua/frecency/frecency.lua
- lua/frecency/tests/frecency_spec.lua
> feat: add an command to delete an entry from DB

- README.md
- lua/frecency/picker.lua
- lua/frecency/sorters.lua
> feat: match like 'smartcase'

- README.md
> docs: add instructions to launch frecency via Lua

- README.md
- lua/frecency/config.lua
- lua/frecency/recency.lua
I think the original recency_values is not goods for me.so want to customize this recency_values.
> feat(recency_values): customize recency_values

- lua/frecency/entry_maker.lua
- lua/frecency/picker.lua
- lua/frecency/types.lua
See #192
See https://github.com/nvim-telescope/telescope.nvim/pull/3010
> Support path_display: `filename_first`

- lua/frecency/finder.lua
> feat: use fd over than rg because fd is faster

- lua/frecency/entry_maker.lua
> fix loaded buffers highlight

- doc/telescope-frecency.txt
- lua/frecency/config.lua
You can see notes in writing your own configs.
> docs: add note for FrecencyOpts

- doc/telescope-frecency.txt
- lua/frecency/finder.lua
Fixes https://github.com/nvim-telescope/telescope-frecency.nvim/issues/211
> Exclude `.git` for default `fd` command

- lua/frecency/init.lua
> fix: delay setup not to avoid bg color detection

- doc/telescope-frecency.txt
See https://www.reddit.com/r/neovim/comments/1egczrs/how_to_sort_files_in_telescope_by_showing_the/
> docs: add note for disabling the dialog

- lua/frecency/database.lua
> refactor: follow up #244 to reduce calling funcs

- lua/frecency/database.lua
- lua/frecency/database/table.lua
- lua/frecency/entry_maker.lua
- lua/frecency/file_lock.lua
- lua/frecency/finder.lua
- lua/frecency/fs.lua
- lua/frecency/fuzzy_sorter.lua
- lua/frecency/init.lua
- lua/frecency/klass.lua
- lua/frecency/lazy_require.lua
- lua/frecency/log.lua
- lua/frecency/os_util.lua
- lua/frecency/picker.lua
- lua/frecency/recency.lua
- lua/frecency/substr_sorter.lua
- lua/frecency/tests/frecency_spec.lua
- lua/frecency/tests/recency_spec.lua
- lua/frecency/tests/util.lua
- lua/frecency/timer.lua
- lua/frecency/types.lua
- lua/frecency/wait.lua
- lua/frecency/watcher.lua
- lua/frecency/web_devicons.lua
> feat: make query() faster and more lazier

- lua/frecency/init.lua
- lua/frecency/klass.lua
> fix: detect async context more robustly

- lua/frecency/config.lua
- lua/frecency/database.lua
- lua/frecency/init.lua
- lua/frecency/klass.lua
- lua/frecency/timer.lua
- lua/frecency/wait.lua
> feat: separate bootstrap logic to launch faster

- lua/frecency/picker.lua
> fix: work with default_workspace and workspace tag
